events/urls.py
from django.conf.urls import url
from . import views

app_name = "events"

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^subscribe/(?:(?P<code>[a-zA-Z0-9]+)/)?$", views.subscribe, name="subscribe"),
    url(r"^unsubscribe/(?P<code>[a-zA-Z0-9]+)/$", views.unsubscribe, name="unsubscribe"),
]

ubine/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('events.urls')),
    url(r'^locate/', include('locate.urls')),
]

events/models.py
from datetime import datetime

from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db import models
from django.template.loader import get_template
from django.utils.crypto import get_random_string
from django.utils.timezone import localtime


EMAIL_SENDER = "UBinE Events <events@ubine.ml>"

class Event(models.Model):
    # What?
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=5000)

    # Where?
    location = models.CharField(max_length=50)

    # When?
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True)

    # Who?
    # TODO: contacts/organizers

    # Notifications
    # subscribers = models.ManyToManyField("Subscriber")

    def __str__(self):
        return "%(title)s (%(time)s)" % {
            "title": self.title,
            "time": " at ".join(Event.format_datetime(self.start_time))  # self.duration
        }

    @staticmethod
    def format_datetime(dt):
        date = datetime.strftime(localtime(dt), "%A, %B %d, %Y")
        time = datetime.strftime(localtime(dt), "%I:%M %p")
        yield from (date, time)

    @property
    def duration(self):
        """Returns a string representing the duration of the event"""
        dt = dict()
        dt["start_date"], dt["start_time"] = Event.format_datetime(self.start_time)
        if self.end_time:
            dt["end_date"], dt["end_time"] = Event.format_datetime(self.end_time)
            if self.start_time.date() == self.end_time.date():
                duration = "%(start_date)s, from %(start_time)s to %(end_time)s"
            else:
                duration = "%(start_date)s at %(start_time)s to %(end_date)s at %(end_time)s"
        else:
            duration = "%(start_date)s at %(start_time)s"
        return duration % dt

    def save(self, *args, **kwargs):
        subscribers = Subscriber.objects.filter(opted_in=True)
        for subscriber in subscribers.all():
            send_mail(
                "Event on UBinE: %s" % self.title,
                self.description,
                EMAIL_SENDER,
                [subscriber.email_address]
            )
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["-start_time", "-end_time"]


class Subscriber(models.Model):
    """A subscriber is one who subscribes to events.

    Attributes:
        email_address: The email address of the subscriber.
        email_confirmed: If the subscriber has confirmed his/her email address.
        code: The last assigned confirmation/unsubscription code.
    """

    CODE_LENGTH = 25

    email_address = models.EmailField(unique=True)
    opted_in = models.BooleanField(default=False)
    code = models.CharField(max_length=CODE_LENGTH, unique=True)
    # code_updated = models.DateTimeField()  # TODO: update doc when enabled

    # TODO: add a way to allow users to limit their subscription

    def __str__(self):
        return self.email_address

    @staticmethod
    def build_url(request, view, code):
        return request.build_absolute_uri(
            reverse("events:%s" % view, args=(code,))
        )

    @classmethod
    def create(cls, email_address, request):
        if not Subscriber.objects.filter(email_address=email_address).exists():
            subscriber = cls(email_address=email_address)
            subscriber.save()
            if subscriber.code:
                body_text = get_template("events/emails/subscribe_confirm.txt")
                context = {
                    "url": Subscriber.build_url(request, "subscribe", subscriber.code)
                }
                return send_mail(
                    "UBinE Events Subscription Confirmation",
                    body_text.render(context),
                    EMAIL_SENDER,
                    [subscriber.email_address]
                )
        return False

    def opt_in(self, request):
        if not self.opted_in:
            self.opted_in = True
            self.generate_code()
            self.save()
            body_text = get_template("events/emails/subscribe_confirmed.txt")
            context = {
                "url": Subscriber.build_url(request, "unsubscribe", self.code)
            }
            return send_mail(
                "UBinE Events Subscription Confirmation",
                body_text.render(context),
                EMAIL_SENDER,
                [self.email_address]
            )
        return False

    def opt_out(self, request):
        if self.opted_in:
            self.opted_in = False
            self.generate_code()
            self.save()
            body_text = get_template("events/emails/unsubscribed.txt")
            context = {
                "url": Subscriber.build_url(request, "subscribe", self.code)
            }
            return send_mail(
                "UBinE Events Unsubscription Confirmation",
                body_text.render(context),
                EMAIL_SENDER,
                [self.email_address]
            )
        return False

    def generate_code(self):
        while True:
            code = get_random_string(length=Subscriber.CODE_LENGTH)
            if not Subscriber.objects.filter(code=code).exists():
                self.code = code
                return

    def save(self, *args, **kwargs):
        if not self.code:
            self.generate_code()
        super().save(*args, **kwargs)

events/forms.py
from django import forms


class SubscriptionForm(forms.Form):
    email_address = forms.EmailField()

events/views.py
from datetime import datetime

from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.http.response import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from events.forms import SubscriptionForm
from events.models import Event, Subscriber


def index(request):
    events = Event.objects.all()

    if request.GET.get("id"):
        events = events.filter(id=request.GET["id"])
    if request.GET.get("title"):
        events = events.filter(title__contains=request.GET["title"])
    if request.GET.get("after"):
        try:
            date_after = datetime.strptime(request.GET["after"], "%Y-%m-%d")
        except ValueError:
            pass
        else:
            date_after = timezone.make_aware(date_after, timezone.get_current_timezone())
            events = events.filter(start_time__gte=date_after)
    if request.GET.get("before"):
        try:
            date_before = datetime.strptime(request.GET["before"], "%Y-%m-%d")
        except ValueError:
            pass
        else:
            date_before = timezone.make_aware(date_before, timezone.get_current_timezone())
            events = events.filter(end_time__lt=date_before)

    return render(request, "events/events.html", {
        "events": events,
        "query": request.GET
    })


def subscribe(request, code=None):
    if code:
        subscriber = Subscriber.objects.filter(code=code).first()
        if subscriber and subscriber.opt_in(request):
            return render(request, "events/subscribed.html", {"unsubscribe": subscriber.code})
        return render(request, "events/subscribed.html")
    else:
        if request.method == "POST":
            form = SubscriptionForm(request.POST)
            if form.is_valid():
                email_address = form.cleaned_data["email_address"]
                try:
                    validate_email(email_address)
                except ValidationError:
                    pass
                else:
                    if Subscriber.create(email_address, request):
                        return HttpResponse("Valid")
                    else:
                        return HttpResponse("Duplicate or email could not be sent")
        else:
            form = SubscriptionForm()
        return render(request, "events/subscribe.html", {
            "form": form
        })


def unsubscribe(request, code):
    subscriber = Subscriber.objects.filter(code=code).first()
    if subscriber:
        if subscriber.opt_out(request):
            return render(request, "events/unsubscribe.html", {"resubscribe": subscriber.code})
    return render(request, "events/unsubscribe.html")

events/templates/events/events.html
{% extends "base.html" %}

{% load markdown_deux_tags %}
{% load staticfiles %}

{% block title %}Events | {% endblock %}

{% block content %}
    <h2>Events</h2>

    <form action="{% url "events:index" %}" method="get">
        <fieldset class="fieldset">
            <legend>Filter Results</legend>
            <label class="medium-6 large-3 columns">
                ID
                <input type="number" name="id" value="{{ query.id }}">
            </label>
            <label class="medium-6 large-3 columns">
                Title
                <input type="text" name="title" value="{{ query.title }}">
            </label>
            <label class="medium-6 large-3 columns">
                Events after
                <input type="datetime-local" name="after" class="search-date"
                       placeholder="YYYY-MM-DD" data-date-format="yyyy-mm-dd" value="{{ query.after }}">
            </label>
            <label class="medium-6 large-3 columns">
                Events before
                <input type="datetime-local" name="before" class="search-date"
                       placeholder="YYYY-MM-DD" data-date-format="yyyy-mm-dd" value="{{ query.before }}">
            </label>
            <button class="button expanded">Search</button>
        </fieldset>
    </form>

    <div class="text-center">
        <a href="{% url "events:subscribe" %}" class="button secondary hollow">Subscribe to All Events Posted on UBinE</a>
    </div>

    {% if events %}
        {% for event in events %}
            <section class="callout">
                <h3>{{ event.title }}</h3>
                <p class="events-duration">{{ event.duration }}</p>
                <p class="events-description">{{ event.description|markdown }}</p>
            </section>
        {% endfor %}
    {% else %}
        <p class="callout alert">There are no events that match your search query.</p>
    {% endif %}
{% endblock %}

{% block extra_stylesheets %}
    <link rel="stylesheet" href="{% static "foundation-icons/foundation-icons.css" %}">
    <link rel="stylesheet" href="{% static "css/foundation-datepicker.min.css" %}">
    <style>
        .datepicker td.active.day {
            background-color: rgb(0, 91, 187);
            color: white;
        }
    </style>
{% endblock %}

{% block extra_javascript %}
    <script src="{% static "js/foundation-datepicker.min.js" %}"></script>
    <script>
        $(function() {
            $(".search-date").fdatepicker();
        })
    </script>
{% endblock %}

events/templates/events/subscribe.html
{% extends "base.html" %}
{% block title %}Subscribe to Events | {% endblock %}
{% block content %}
    <h2>Subscribe to Events</h2>

    <form action="{% url "events:subscribe" %}" method="post">
        <fieldset class="fieldset">
            <legend>Subscribe to Events</legend>

            <p>
                UBinE will notify you whenever an event is posted or modified.
                <em>You will be required to verify your email address, but you may unsubscribe at any time.</em>
            </p>

            {% csrf_token %}
            {{ form.as_p }}
            <button class="button expanded">Subscribe</button>
        </fieldset>
    </form>
{% endblock %}

events/templates/events/subscribed.html
{% extends "base.html" %}
{% block title %}Subscribe to Events | {% endblock %}
{% block content %}
    <h2>Subscribe to Events</h2>

    {% if unsubscribe %}
        <p class="callout success">
            You are now subscribed to UBinE Events notifications.
            You may click <a href="{% url "events:unsubscribe" unsubscribe %}">here</a> to unsubscribe.
        </p>
    {% else %}
        <p class="callout alert">
            There was an issue confirming your subscription.
            Please verify that your code is correct.
            If it is, then you may have already been subscribed.
        </p>
    {% endif %}
{% endblock %}

events/templates/events/unsubscribe.html
{% extends "base.html" %}
{% block title %}Unsubscribe from Events | {% endblock %}
{% block content %}
    <h2>Unsubscribe from Events</h2>

    {% if resubscribe %}
        <p class="callout success">
            You are now unsubscribed from UBinE Events notifications.
            You may click <a href="{% url "events:subscribe" resubscribe %}">here</a> to re-subscribe.
        </p>
    {% else %}
        <p class="callout alert">
            There was an issue with unsubscribing you.
            Please verify that your code is correct.
            If it is, then you may have already been unsubscribed.
        </p>
    {% endif %}
{% endblock %}