events/urls.py
from django.conf.urls import url
from . import views

app_name = "events"

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^subscribe/(?:(?P<code>[a-zA-Z0-9]+)/)?$", views.subscribe, name="subscribe"),
    url(r"^unsubscribe/(?P<code>[a-zA-Z0-9]+)/$", views.unsubscribe, name="unsubscribe"),
]

locate/urls.py
from django.conf.urls import url
from . import views

app_name = "locate"

urlpatterns = [
    url(r"^$", views.index, name="index")
]

ubine/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('events.urls')),
    url(r'^locate/', include('locate.urls')),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}UBinE</title>
    <link rel="stylesheet" href="{% static "css/foundation.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block extra_stylesheets %}{% endblock %}
</head>
<body>
    <header>
        <h1 class="row"><a href="{% url "index" %}">UBinE</a></h1>
    </header>
    <main class="row">
        {% block content %}{% endblock %}
    </main>
    <footer class="row text-center">
        Disclaimer:
            The contents and link identifiers of this web page are not monitored,
            reviewed, nor endorsed by the State University of New York at Buffalo.
    </footer>

    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/what-input.js" %}"></script>
    <script src="{% static "js/foundation.min.js" %}"></script>
    <script>
      $(document).foundation();
    </script>
    {% block extra_javascript %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h2>Welcome to UBinE!</h2>

    <div class="medium-6 columns">
        <a href="{% url "events:index" %}" class="button expanded">Find Events</a>
    </div>
    <div class="medium-6 columns">
        <a href="{% url "locate:index" %}" class="button expanded">Locate Rooms</a>
    </div>
{% endblock %}